/**
 * Storage layer types for the SWE-Squad Memory Service.
 *
 * Interfaces mirror the Supabase schema defined in
 * memory/sql/001_memory_tables.sql with TypeScript-idiomatic naming.
 * All rows include team_id for multi-tenant scoping — no operation
 * may proceed without a non-empty team_id.
 */

// ---------------------------------------------------------------------------
// Row types — direct mappings from DB columns
// ---------------------------------------------------------------------------

/** Mirrors memory_sessions table. */
export interface SessionRow {
  id: number;
  team_id: string;
  content_session_id: string;
  memory_session_id: string;
  project: string;
  platform_source: string;
  agent_id: string | null;
  user_prompt: string | null;
  status: 'active' | 'completed' | 'failed' | 'orphaned';
  started_at_epoch: number;
  completed_at_epoch: number | null;
}

/** Mirrors memory_observations table. */
export interface ObservationRow {
  id: number;
  team_id: string;
  memory_session_id: string;
  project: string;
  type: string | null;
  title: string | null;
  narrative: string | null;
  text: string | null;
  facts: string | null;
  concepts: string | null;
  files_read: string | null;
  files_modified: string | null;
  content_hash: string | null;
  /** pgvector column — returned as a JSON number array via PostgREST. */
  embedding: number[] | null;
  /** Auto-generated by DB trigger — never set directly on INSERT. */
  fts_vector: string | null;
  created_at_epoch: number;
}

/** Mirrors memory_summaries table. */
export interface SummaryRow {
  id: number;
  team_id: string;
  memory_session_id: string;
  project: string;
  request: string | null;
  investigated: string | null;
  learned: string | null;
  completed: string | null;
  next_steps: string | null;
  embedding: number[] | null;
  created_at_epoch: number;
}

/**
 * Row returned by both semantic-search and full-text-search RPCs.
 * The numeric relevance field is named `similarity` for vector results
 * and `rank` for FTS results; the adapter normalises both onto this type.
 */
export interface SearchResult {
  id: number;
  project: string;
  type: string | null;
  title: string | null;
  narrative: string | null;
  facts: string | null;
  concepts: string | null;
  files_read: string | null;
  files_modified: string | null;
  /** Cosine similarity (0–1) from match_memory_observations, or ts_rank from search_memory_observations. */
  similarity: number | null;
  created_at_epoch: number;
}

// ---------------------------------------------------------------------------
// Parameter types — what callers supply to the adapter
// ---------------------------------------------------------------------------

/** Parameters required to open a new memory session. */
export interface CreateSessionParams {
  team_id: string;
  content_session_id: string;
  memory_session_id: string;
  project: string;
  platform_source: string;
  agent_id?: string;
  user_prompt?: string;
}

/** Parameters required to persist an observation. */
export interface StoreObservationParams {
  team_id: string;
  memory_session_id: string;
  project: string;
  type?: string;
  title?: string;
  narrative?: string;
  text?: string;
  facts?: string;
  concepts?: string;
  files_read?: string;
  files_modified?: string;
  /** SHA-256 hex digest of the canonical observation content, used for dedup. */
  content_hash?: string;
  /** Pre-computed bge-m3 embedding (1024 dimensions). */
  embedding?: number[];
  platform_source?: string;
}

/** Parameters required to persist a session summary. */
export interface StoreSummaryParams {
  team_id: string;
  memory_session_id: string;
  project: string;
  request?: string;
  investigated?: string;
  learned?: string;
  completed?: string;
  next_steps?: string;
}

// ---------------------------------------------------------------------------
// Adapter interface
// ---------------------------------------------------------------------------

/**
 * Provider-agnostic storage contract for the memory service.
 *
 * All methods MUST reject (throw) when `teamId` is empty or undefined —
 * cross-tenant data leaks are a security violation.
 *
 * Non-critical methods (observation writes, search) SHOULD log errors and
 * return graceful fallbacks (null / empty array) rather than crashing the
 * caller, since memory is best-effort infrastructure.
 */
export interface StorageAdapter {
  /**
   * Open or upsert a memory session.
   *
   * If the (team_id, content_session_id) pair already exists, the
   * existing row is returned (idempotent).
   *
   * @returns The database row id and the stable UUID used as FK.
   */
  createSession(
    params: CreateSessionParams,
  ): Promise<{ sessionDbId: number; memorySessionId: string }>;

  /**
   * Fetch a session row by its external content_session_id.
   *
   * @returns The session row, or null if not found.
   */
  getSessionByContentId(
    teamId: string,
    contentSessionId: string,
  ): Promise<SessionRow | null>;

  /**
   * Mark a session as completed and record the finish time.
   */
  completeSession(teamId: string, contentSessionId: string): Promise<void>;

  /**
   * Persist a single observation.
   *
   * Returns null (no-op) when a duplicate content_hash was seen within the
   * last 30 seconds (dedup window). Returns the new row id and epoch ms
   * otherwise.
   */
  storeObservation(
    params: StoreObservationParams,
  ): Promise<{ id: number; createdAtEpoch: number } | null>;

  /**
   * Full-text search via the `search_memory_observations` RPC.
   *
   * @param teamId   Required — scopes the query.
   * @param query    FTS query string (websearch_to_tsquery syntax accepted).
   * @param project  Optional project filter.
   * @param type     Optional observation type filter.
   * @param limit    Max rows to return (default 50).
   */
  searchObservations(
    teamId: string,
    query: string,
    project?: string,
    type?: string,
    limit?: number,
  ): Promise<SearchResult[]>;

  /**
   * Vector similarity search via the `match_memory_observations` RPC.
   *
   * @param teamId    Required — scopes the query.
   * @param embedding Pre-computed bge-m3 query vector (1024 dimensions).
   * @param project   Optional project filter.
   * @param topK      Max rows to return (default 10).
   * @param threshold Minimum cosine similarity to include (default 0.70).
   */
  semanticSearch(
    teamId: string,
    embedding: number[],
    project?: string,
    topK?: number,
    threshold?: number,
  ): Promise<SearchResult[]>;

  /**
   * Fetch the most recently created observations for a project, ordered by
   * created_at_epoch descending.
   *
   * @param limit Max rows to return (default 20).
   */
  getRecentObservations(
    teamId: string,
    project: string,
    limit?: number,
  ): Promise<SearchResult[]>;

  /**
   * Persist a session summary.
   *
   * @returns The database row id of the new summary.
   */
  storeSummary(params: StoreSummaryParams): Promise<{ id: number }>;
}
