/**
 * Tool: delegate_development — Delegate fix development to a configured engine.
 *
 * Engine-agnostic: reads config.delegation.developer.engine to resolve
 * which CodingEngine to use. Never imports an engine directly.
 */

import { defineTool } from "@mariozechner/pi-coding-agent";
import { Type } from "@sinclair/typebox";
import { execFileSync } from "node:child_process";
import type { SWEContext } from "../shared/context.js";
import { resolveEngineForRole, getDelegationConfig } from "../shared/engine-resolver.js";
import { buildDevelopmentPrompt } from "../shared/prompt-builder.js";
import { withRetry } from "../utils/retry.js";

/**
 * Post-development git workflow: if the engine left uncommitted changes,
 * create a branch, commit, push, and create a PR.
 *
 * Returns the PR URL if a PR was created, null otherwise.
 */
function postDevGitWorkflow(
  ticketId: string,
  title: string,
  workspace: string,
  repo: string | undefined,
  githubIssue?: number,
): { prUrl: string | null; branch: string | null } {
  const execOpts = { cwd: workspace, encoding: "utf-8" as const, stdio: "pipe" as const, timeout: 30_000 };
  try {
    // Check if there are any changes (staged, unstaged, or untracked)
    const status = execFileSync("git", ["status", "--porcelain"], execOpts).trim();
    if (!status) return { prUrl: null, branch: null };

    // Check if already on a feature branch (engine may have created one)
    const currentBranch = execFileSync("git", ["rev-parse", "--abbrev-ref", "HEAD"], execOpts).trim();
    let branch = currentBranch;

    // If still on main/master, create a feature branch — never commit on main
    if (branch === "main" || branch === "master") {
      branch = `swe-fix/ticket-${ticketId}`;
      try {
        execFileSync("git", ["checkout", "-b", branch], execOpts);
      } catch {
        // Branch may already exist — try switching to it
        try {
          execFileSync("git", ["checkout", branch], execOpts);
        } catch {
          // Both failed — refuse to commit on main
          return { prUrl: null, branch: null };
        }
      }
    }

    // Stage and commit all changes
    execFileSync("git", ["add", "-A"], execOpts);
    const commitMsg = `feat: ${title}\n\nTicket: ${ticketId}\nAutomated by SWE-Manager delegate_development`;
    execFileSync("git", ["commit", "-m", commitMsg, "--allow-empty"], execOpts);

    // Push
    try {
      execFileSync("git", ["push", "-u", "origin", branch], execOpts);
    } catch {
      // Push failed — maybe no remote access, continue without PR
      return { prUrl: null, branch };
    }

    // Create PR using gh CLI
    try {
      const closeRef = githubIssue && repo ? `\n\nCloses ${repo}#${githubIssue}` : "";
      const prBody = `Automated fix for ticket ${ticketId}.${closeRef}\n\nGenerated by SWE-Manager delegate_development tool.`;
      const prOut = execFileSync(
        "gh",
        ["pr", "create", "--title", title, "--body", prBody, "--base", "main", "--head", branch],
        execOpts,
      ).trim();
      // gh pr create outputs the PR URL
      const prUrlMatch = prOut.match(/https:\/\/github\.com\/[^\s]+\/pull\/\d+/);
      return { prUrl: prUrlMatch ? prUrlMatch[0] : null, branch };
    } catch {
      return { prUrl: null, branch };
    }
  } catch {
    return { prUrl: null, branch: null };
  }
}

export function createDelegateDevelopmentTool(ctx: SWEContext) {
  return defineTool({
    name: "delegate_development",
    label: "Delegate Development",
    description:
      "Delegate fix development for a ticket to the configured development engine. " +
      "Requires a completed investigation report. Creates workspace, runs engine, " +
      "verifies tests, commits, pushes, and creates a PR.",
    parameters: Type.Object({
      ticketId: Type.String({ description: "The ticket ID to develop a fix for" }),
      workspace: Type.Optional(
        Type.String({ description: "Explicit workspace path. Auto-created if omitted." }),
      ),
      model: Type.Optional(
        Type.String({ description: "Model override (e.g. sonnet, opus)" }),
      ),
      timeout: Type.Optional(
        Type.Number({ description: "Timeout in seconds (default 3600)", default: 3600 }),
      ),
    }),
    async execute(_toolCallId, params, _signal, _onUpdate, _extCtx) {
      const startMs = Date.now();
      const store = ctx.ticketStore;
      if (!store) {
        return {
          content: [{ type: "text" as const, text: "Error: Supabase ticket store not configured" }],
          details: {},
        };
      }

      try {
        // 1. Get ticket and verify investigation exists
        const ticket = await store.get(params.ticketId);
        if (!ticket) {
          return {
            content: [{ type: "text" as const, text: `Ticket not found: ${params.ticketId}` }],
            details: {},
          };
        }

        // Rework iterations (changes_requested) don't need an investigation report —
        // the review feedback serves as the guide. Only require investigation for first dev.
        const meta0 = ticket.metadata as Record<string, unknown>;
        const isRework = meta0.reviewVerdict === "changes_requested";
        if (!ticket.investigationReport && !isRework) {
          return {
            content: [{
              type: "text" as const,
              text: `Ticket ${params.ticketId} has no investigation report. Run delegate_investigation first.`,
            }],
            details: {},
          };
        }

        // 2. Claim atomically
        const agentId = ctx.config.teamId;
        const claimed = await store.claimTicket(params.ticketId, agentId);
        if (!claimed) {
          return {
            content: [{ type: "text" as const, text: `Already claimed by another agent: ${params.ticketId}` }],
            details: {},
          };
        }

        // 3. Resolve engine from config
        let engine;
        try {
          engine = resolveEngineForRole("developer", ctx.config);
        } catch (err) {
          await store.releaseTicket(params.ticketId, ticket.status);
          return {
            content: [{ type: "text" as const, text: `Engine resolution failed: ${err}` }],
            details: {},
          };
        }

        // 4. Determine workspace — resolve from ticket repo → config repos → fallback to cwd
        let workspace = params.workspace ?? ctx.cwd;
        if (!params.workspace) {
          const ticketRepo = (ticket.metadata as Record<string, unknown>)?.repo as string | undefined;
          if (ticketRepo) {
            const repoConfig = ctx.config.repos.find(
              (r: Record<string, unknown>) =>
                r.name === ticketRepo || (r.name as string)?.endsWith(`/${ticketRepo.split("/").pop()}`),
            );
            // Config loader converts snake_case → camelCase, so check both forms
            const localPath = repoConfig?.localPath ?? repoConfig?.local_path;
            if (localPath) {
              workspace = String(localPath).replace("~", process.env.HOME ?? "/home/agent");
            }
          }
        }

        // 5. Query memory for relevant fix patterns
        let memoryContext = "";
        if (ctx.memoryService) {
          try {
            const memories = await ctx.memoryService.query({
              tenantId: ctx.config.teamId,
              projectId: (ticket.metadata as Record<string, unknown>).repo as string ?? "default",
              types: ["fix_pattern", "investigation", "root_cause"],
              limit: 5,
            });
            if (memories.length > 0) {
              memoryContext = "\n\n## Relevant Past Fixes & Patterns\n\n" +
                memories.map((m, i) =>
                  `### Memory ${i + 1} (confidence: ${m.confidence}, type: ${m.type})\n${m.content.slice(0, 500)}`
                ).join("\n\n");
              ctx.logger.info(
                `Memory: injected ${memories.length} past fix patterns into dev prompt for ${params.ticketId}`,
              );
              for (const m of memories) {
                ctx.memoryService.recordHit(m.id, ctx.config.teamId).catch(() => {});
              }
            } else {
              ctx.logger.debug(`Memory: no relevant fix patterns found for ${params.ticketId}`);
            }
          } catch (e) {
            ctx.logger.warn(`Memory query failed (non-fatal): ${e}`);
          }
        }

        // 6. Build prompt and run
        const delegation = getDelegationConfig("developer", ctx.config);
        const prompt = buildDevelopmentPrompt(ticket, workspace) + memoryContext;
        const model = params.model ?? delegation.model;
        const timeout = params.timeout ?? delegation.timeout;

        ctx.logger.info(
          `Developing fix for ${params.ticketId} via ${engine.name} ` +
            `(model=${model ?? "default"}, timeout=${timeout}s, cwd=${workspace})`,
        );

        const result = await engine.run(prompt, {
          cwd: workspace,
          model,
          timeout,
        });

        // 6. Check result
        if (result.returncode !== 0) {
          ticket.status = "in_development";
          ticket.updatedAt = new Date().toISOString();
          const meta = ticket.metadata as Record<string, unknown>;
          meta.lastDevError = result.stderr || "Engine returned non-zero";
          await withRetry(() => store.update(ticket), { label: "store.update after dev failure" });
          await withRetry(
            () => store.releaseTicket(params.ticketId, "in_development"),
            { label: "releaseTicket after dev failure" },
          );

          ctx.outcomeTracker?.record({
            tool: "delegate_development",
            ticketId: params.ticketId,
            engine: engine.name,
            success: false,
            error: result.stderr || "non-zero exit",
            durationMs: Date.now() - startMs,
            costUsd: result.costUsd ?? undefined,
            timestamp: new Date(),
          });

          return {
            content: [{
              type: "text" as const,
              text: `Development failed for ${params.ticketId}: ${result.stderr || "non-zero exit"}\n` +
                `Engine: ${engine.name}, returncode=${result.returncode}`,
            }],
            details: { ticketId: params.ticketId, returncode: result.returncode },
          };
        }

        // 6b. Validate engine produced meaningful output or git changes
        const stdout = result.stdout || "";
        const hasOutput = stdout.trim().length > 50; // more than trivial output
        let hasGitChanges = false;
        try {
          const gitStatus = execFileSync(
            "git", ["status", "--porcelain"],
            { cwd: workspace, encoding: "utf-8", stdio: "pipe", timeout: 10_000 },
          ).trim();
          hasGitChanges = gitStatus.length > 0;
        } catch { /* git check failure — non-fatal, rely on output check */ }

        if (!hasOutput && !hasGitChanges) {
          ticket.status = "in_development";
          ticket.updatedAt = new Date().toISOString();
          const emptyMeta = ticket.metadata as Record<string, unknown>;
          emptyMeta.lastDevError = "Engine returned 0 but produced no output and no git changes";
          await withRetry(() => store.update(ticket), { label: "store.update after empty dev" });
          await withRetry(
            () => store.releaseTicket(params.ticketId, "in_development"),
            { label: "releaseTicket after empty dev" },
          );

          ctx.outcomeTracker?.record({
            tool: "delegate_development",
            ticketId: params.ticketId,
            engine: engine.name,
            success: false,
            error: "empty output, no git changes",
            durationMs: Date.now() - startMs,
            costUsd: result.costUsd ?? undefined,
            timestamp: new Date(),
          });

          return {
            content: [{
              type: "text" as const,
              text: `Development produced no output for ${params.ticketId}. ` +
                `Engine returned 0 but stdout was empty and no git changes detected.\n` +
                `Engine: ${engine.name}`,
            }],
            details: { ticketId: params.ticketId, returncode: 0, emptyResult: true },
          };
        }

        // 7. Extract PR URL from engine output (if the engine created a PR)
        const prUrlMatch = stdout.match(/https:\/\/github\.com\/[^\s)]+\/pull\/\d+/);
        const meta = ticket.metadata as Record<string, unknown>;
        if (prUrlMatch) {
          meta.prUrl = prUrlMatch[0];
          const prNumMatch = prUrlMatch[0].match(/\/pull\/(\d+)/);
          if (prNumMatch) meta.prNumber = parseInt(prNumMatch[1], 10);
        }
        // Also try to detect branch name from output (avoid matching "PR" or "HEAD")
        const branchMatch = stdout.match(/(?:branch|pushed to|->)\s+['"]?((?:swe-fix|fix|feat|bugfix|hotfix)[/][a-zA-Z0-9/_-]+)['"]?/i);
        if (branchMatch) {
          meta.devBranch = branchMatch[1];
        } else {
          // Fallback: detect from git current branch in workspace
          try {
            const currentBr = execFileSync("git", ["rev-parse", "--abbrev-ref", "HEAD"],
              { cwd: workspace, encoding: "utf-8", stdio: "pipe", timeout: 10_000 }).trim();
            if (currentBr !== "main" && currentBr !== "master" && currentBr !== "HEAD") {
              meta.devBranch = currentBr;
            }
          } catch { /* non-fatal */ }
        }
        meta.devEngine = engine.name;
        meta.devCost = result.costUsd;
        meta.developedAt = new Date().toISOString();

        // 7b. Git workflow: commit/push any uncommitted changes and create PR if needed.
        // Always run — even on rework (prUrl already set), the engine may leave
        // unstaged changes that need to be committed and pushed to the existing branch.
        {
          const ticketRepo = (ticket.metadata as Record<string, unknown>)?.repo as string | undefined;
          const tmeta = ticket.metadata as Record<string, unknown>;
          const ghIssue = (tmeta?.github_issue ?? tmeta?.issueNumber) as number | undefined;
          const gitResult = postDevGitWorkflow(
            params.ticketId,
            ticket.title,
            workspace,
            ticketRepo,
            ghIssue,
          );
          if (gitResult.prUrl && !meta.prUrl) meta.prUrl = gitResult.prUrl;
          if (gitResult.branch) meta.devBranch = gitResult.branch;
        }

        // 7c. If we still don't have a PR URL, try looking up existing PRs on the branch
        if (!meta.prUrl && meta.devBranch && (ticket.metadata as Record<string, unknown>)?.repo) {
          try {
            const lookupRepo = (ticket.metadata as Record<string, unknown>).repo as string;
            const prListOut = execFileSync(
              "gh",
              ["pr", "list", "--head", meta.devBranch as string, "--repo", lookupRepo,
               "--json", "url,number", "--limit", "1"],
              { cwd: workspace, encoding: "utf-8", stdio: "pipe", timeout: 15_000 },
            ).trim();
            const prList = JSON.parse(prListOut);
            if (Array.isArray(prList) && prList.length > 0) {
              meta.prUrl = prList[0].url;
              meta.prNumber = prList[0].number;
            }
          } catch { /* non-fatal — PR lookup failure doesn't block ticket update */ }
        }

        // Also extract prNumber from prUrl if we have the URL but not the number
        if (meta.prUrl && !meta.prNumber) {
          const prMatch = (meta.prUrl as string).match(/\/pull\/(\d+)/);
          if (prMatch) meta.prNumber = parseInt(prMatch[1], 10);
        }

        // 7d. Return to main branch so subsequent heartbeats operate on clean main
        try {
          const currentBr = execFileSync("git", ["rev-parse", "--abbrev-ref", "HEAD"],
            { cwd: workspace, encoding: "utf-8", timeout: 10_000 }).trim();
          if (currentBr !== "main" && currentBr !== "master") {
            execFileSync("git", ["checkout", "main"], { cwd: workspace, encoding: "utf-8", stdio: "pipe", timeout: 10_000 });
          }
        } catch { /* non-fatal — workspace may be a worktree */ }

        // 8. Update ticket (retry — connection may be stale after long engine.run)
        // Clear stale review metadata so the next heartbeat delegates a fresh review
        // instead of looping back to development.
        delete meta.reviewVerdict;
        delete meta.reviewSummary;
        delete meta.reviewRawOutput;
        delete meta.reviewSeverity;
        delete meta.reviewIssuesFound;
        delete meta.reviewedAt;
        delete meta.reviewEngine;
        delete meta.reviewCost;
        ticket.status = "in_review";
        ticket.developmentSessionId = result.sessionId ?? null;
        ticket.metadata = meta;
        ticket.updatedAt = new Date().toISOString();
        await withRetry(() => store.update(ticket), { label: "store.update after development" });

        await withRetry(
          () => store.releaseTicket(params.ticketId, "in_review"),
          { label: "releaseTicket after development" },
        );

        // Store successful fix pattern in memory for future reuse
        if (ctx.memoryService && result.stdout) {
          try {
            await ctx.memoryService.store(
              ctx.config.teamId,
              (ticket.metadata as Record<string, unknown>).repo as string ?? "default",
              {
                agentId: ctx.config.teamId,
                engine: engine.name,
                type: "fix_pattern",
                content: `Fix for ${ticket.title} (${params.ticketId}):\n${result.stdout.slice(0, 2000)}`,
                tags: ["fix_pattern", ticket.severity, params.ticketId],
              },
            );
            ctx.logger.info(`Memory: stored fix pattern for ${params.ticketId}`);
          } catch (e) {
            ctx.logger.warn(`Memory store failed (non-fatal): ${e}`);
          }
        }

        ctx.outcomeTracker?.record({
          tool: "delegate_development",
          ticketId: params.ticketId,
          engine: engine.name,
          success: true,
          durationMs: Date.now() - startMs,
          costUsd: result.costUsd ?? undefined,
          timestamp: new Date(),
        });

        return {
          content: [{
            type: "text" as const,
            text: `Development complete for ${params.ticketId}.\n\n` +
              `Engine: ${engine.name}, Cost: $${result.costUsd?.toFixed(4) ?? "unknown"}\n\n` +
              `Output:\n${(result.stdout || "").slice(0, 500)}`,
          }],
          details: {
            ticketId: params.ticketId,
            engine: engine.name,
            cost: result.costUsd,
            model: result.model,
          },
        };
      } catch (err) {
        // Return to main on failure too
        try {
          execFileSync("git", ["checkout", "main"], { cwd: ctx.cwd, encoding: "utf-8", stdio: "pipe", timeout: 10_000 });
        } catch { /* non-fatal */ }

        ctx.outcomeTracker?.record({
          tool: "delegate_development",
          ticketId: params.ticketId,
          success: false,
          error: String(err),
          durationMs: Date.now() - startMs,
          timestamp: new Date(),
        });

        // Store error in ticket metadata so it's visible in ticket_list
        try {
          const ticket = await store.get(params.ticketId);
          if (ticket) {
            const meta = ticket.metadata as Record<string, unknown>;
            meta.lastDevError = String(err).slice(0, 500);
            ticket.metadata = meta;
            ticket.updatedAt = new Date().toISOString();
            await store.update(ticket);
          }
        } catch { /* non-fatal — best effort error recording */ }

        try {
          await store.releaseTicket(params.ticketId);
        } catch { /* non-fatal */ }

        return {
          content: [{ type: "text" as const, text: `Development failed for ${params.ticketId}: ${err}` }],
          details: {},
        };
      }
    },
  });
}
